In [10]:
import json
import numpy as np
with open('./nknews/nknews/news.json','r',encoding='utf-8')as fp:
    json_data = json.load(fp)
len = len(json_data)

mat = np.zeros((len,len))
for i in range(len):
    for j in range(len):
        if json_data[i]['url'][0] in json_data[j]['links']:
            mat[i][j] = 1

In [5]:
o = np.sum(mat,axis=0)
print(o)

[4762. 4762. 4762. ... 4762. 4762. 4762.]


In [10]:
max(mat[13985])

0.0

In [4]:
G=np.array([[0,0,1],[1,0,1],[1,1,0]])
print(G)
print(np.sum(G,axis=0))

[[0 0 1]
 [1 0 1]
 [1 1 0]]
[2 1 2]


In [11]:
def GtoM(G, N):
    M = np.zeros((N, N))
    D = np.sum(G,axis=0)
    for i in range(N):
        for j in range(N):
            if D[j] == 0:
                continue
            M[i][j] = G[i][j] / D[j] # watch out! M_j_i instead of M_i_j
    return M
M = GtoM(G, 3)

In [12]:
ans = GtoM(mat,len)

In [7]:
def PageRank(M, N, T=30000, eps=1e-6, beta=0.8):
    R = np.ones(N) / N
    teleport = np.ones(N) / N
    for time in range(T):
        R_new = beta * np.dot(M, R) + (1-beta)*teleport
        if np.linalg.norm(R_new - R) < eps:
            break
        R = R_new.copy()
    return R_new

In [13]:
rank = PageRank(ans,len)

In [14]:
so=np.argsort(rank)

In [26]:
for i in range(len):
    json_data[i]['influe']=str(so[i])

In [27]:
with open('./nknews/nknews/newssss.json','w') as f:
    json.dump(json_data,f)

In [42]:
mat[13556]

array([1., 1., 1., ..., 1., 1., 1.])

In [1]:
import json
import numpy as np
with open('./nknews/nknews/news.json','r',encoding='utf-8')as fp:
    json_data = json.load(fp)
print(len(json_data))

17280


In [20]:
from elasticsearch.client import Elasticsearch
es = Elasticsearch()
res = es.get(index="newstore-index", id=37832)

In [21]:
print(res['_source'])

{'content': "['\\u3000\\u3000', '（记者 乔仁铭 通讯员 荆克迪\\xa0周敬文\\xa0孙咏琪）近日，我校党史学习教育宣讲团专家深入全校基层单位集中宣讲习近平总书记在庆祝中国共产党成立100周年大会上的重要讲话精神，引导广大师生员工把学习成果转化为奋进新征程、建功新时代的实际行动。', '\\u3000\\u3000日前，我校党史学习教育宣讲团成员、中国特色社会主义经济建设协同创新中心主任逄锦聚教授应邀为机关中心组成员、经济学院作“七一”重要讲话精神宣讲报告。面向机关中心组成员，他以“继续推进马克思主义中国化\\xa0\\xa0实现中华民族伟大复兴——学习习近平总书记在庆祝中国共产党成立100周年大会上的重要讲话”为主题，从“深入学习讲话提出的一系列新观点新要求”“旗帜鲜明地坚持马克思主义”“坚持推进马克思主义中国化”“把讲话作为行动指南为实现中华民族伟大复兴贡献力量”等方面为大家解读了“七一”重要讲话精神，强调应把学习“七一”重要讲话精神与学习马克思主义经典著作结合起来，与推动工作结合起来，在学懂弄通上下功夫，作为全党开展党史学习教育的重要内容，推动学习往深里走、往实里走、往心里走，并扎实做好青年工作。在经济学院，逄锦聚从“深入学习习近平总书记‘七一’重要讲话中提出的一系列新观点新要求”“以‘七一’讲话精神为指导，认真总结中国共产党百年经济理论创新成果和基本经验”“在世界大变局和全面建设社会主义现代化国家进程中发展完善中国经济学”“把‘七一’讲话精神作为行动指南，为实现中华民族伟大复兴贡献力量”四个方面展开宣讲，认真总结并深入解读了习近平总书记在“七一”重要讲话中提出的新观点、新要求，梳理了中国共产党百年经济理论的创新成果。', '\\u3000\\u300011月11日，我校党史学习教育宣讲团成员、马克思主义学院教授盛林深入法学院开展\\xa0“七一”重要讲话精神专题宣讲。他从习近平总书记“七一”重要讲话的重大意义、主要内容、丰富内涵以及其中蕴含的新思想、新观点、新论断、新要求等方面进行阐述，强调总书记讲话站在“两个一百年”历史交汇点，全面回顾了我们党百年走过的光辉历程，深刻阐明了在新征程上推进党和国家事业发展的一系列重大问题，是一篇闪烁着马克思主义真理光芒的光辉文献，是一篇新时代中国共产党人的政治宣言，是一篇新时代坚持和发展中